--liquibase formatted sql

--changeset Armel:1774083097453-1
CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    status      VARCHAR(255),
    created_at  TIMESTAMP,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

